/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated service exports
* Do not edit this file manually
*/
export { AuthService } from "./auth.service";
export { FormationsService } from "./formations.service";
export { GendersService } from "./genders.service";
export { UsersService } from "./users.service";
