/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface ForgotPasswordInput {
    email: string;
}

export interface GenderDTO {
    readonly id: string;
    readonly name: string;
    readonly color: string;
    readonly icon?: string | null;
}

export interface GenderDTOListResponseDTO {
    message: string;
    status: number;
    data?: GenderDTO[];
    count?: number | null;
}

export interface LoginOutputDTO {
    token: string;
    refreshToken: string;
    user: UserResponseDTO;
}

export interface LoginOutputDTOResponseDTO {
    message: string;
    status: number;
    data?: LoginOutputDTO;
    count?: number | null;
}

export interface PasswordRecoveryInput {
    userId: string;
    resetToken: string;
    password: string;
    passwordConfirmation: string;
}

export interface PasswordResetResponseDTO {
    resetToken: string;
    email: string;
    id: string;
}

export interface PasswordResetResponseDTOResponseDTO {
    message: string;
    status: number;
    data?: PasswordResetResponseDTO;
    count?: number | null;
}

export interface StatusAccountDTO {
    readonly id: string;
    readonly name: string;
    readonly color: string;
    readonly icon?: string | null;
}

export interface StringResponseDTO {
    message: string;
    status: number;
    data?: string | null;
    count?: number | null;
}

export interface UserCreateDTO {
    email: string;
    password: string;
    firstName: string;
    lastName: string;
    dataProcessingConsent: boolean;
    privacyPolicyConsent: boolean;
    title?: string | null;
    description?: string | null;
    phoneNumber?: string | null;
    dateOfBirth?: Date;
    roleId?: string;
    genderId?: string;
}

export interface UserInfosWithtoken {
    token: string;
    user: UserResponseDTO;
}

export interface UserInfosWithtokenResponseDTO {
    message: string;
    status: number;
    data?: UserInfosWithtoken;
    count?: number | null;
}

/** Modèle de données pour la connexion utilisateur */
export interface UserLoginDTO {
    /** Adresse email de l'utilisateur (format email valide requis) */
    email: string;
    /** Mot de passe (minimum 8 caractères avec majuscules, minuscules, chiffres) */
    password: string;
}

export interface UserResponseDTO {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
    title?: string | null;
    description?: string | null;
    phoneNumber?: string | null;
    status?: StatusAccountDTO;
    gender?: GenderDTO;
    roles: string[];
}

export interface UserResponseDTOResponseDTO {
    message: string;
    status: number;
    data?: UserResponseDTO;
    count?: number | null;
}

export interface UserUpdateDTO {
    firstName: string;
    lastName: string;
    dateOfBirth: Date;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
