/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface ForgotPasswordInput {
    email: string;
}

export interface LoginOutputDTO {
    token?: string | null;
    refreshToken?: string | null;
    user?: UserResponseDTO;
}

export interface LoginOutputDTOResponseDTO {
    message?: string | null;
    status?: number | null;
    data?: LoginOutputDTO;
    count?: number | null;
}

export interface PasswordRecoveryInput {
    userId: string;
    resetToken: string;
    password: string;
    passwordConfirmation: string;
}

export interface PasswordResetResponseDTO {
    resetToken?: string | null;
    email?: string | null;
    id?: string;
}

export interface PasswordResetResponseDTOResponseDTO {
    message?: string | null;
    status?: number | null;
    data?: PasswordResetResponseDTO;
    count?: number | null;
}

export interface StatusAccountDTO {
    readonly id?: string;
    readonly name?: string | null;
    readonly color?: string | null;
    readonly icon?: string | null;
}

export interface StringResponseDTO {
    message?: string | null;
    status?: number | null;
    data?: string | null;
    count?: number | null;
}

export interface UserCreateDTO {
    email?: string;
    password: string;
    firstName: string;
    lastName: string;
    dateOfBirth?: Date;
    roleId?: string;
}

export interface UserInfosWithtoken {
    token?: string | null;
    user?: UserResponseDTO;
}

export interface UserInfosWithtokenResponseDTO {
    message?: string | null;
    status?: number | null;
    data?: UserInfosWithtoken;
    count?: number | null;
}

/** Modèle de données pour la connexion utilisateur */
export interface UserLoginDTO {
    /** Adresse email de l'utilisateur (format email valide requis) */
    email: string;
    /** Mot de passe (minimum 8 caractères avec majuscules, minuscules, chiffres) */
    password: string;
}

export interface UserResponseDTO {
    id?: string;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    status?: StatusAccountDTO;
    roles?: string[];
}

export interface UserResponseDTOResponseDTO {
    message?: string | null;
    status?: number | null;
    data?: UserResponseDTO;
    count?: number | null;
}

export interface UserUpdateDTO {
    firstName?: string | null;
    lastName?: string | null;
    dateOfBirth?: Date;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
